export { useConsultService } from './consult'
export { useEnterprisesService } from './enterprises'
export { usePaymentsService } from './payments'
export { useIgvAffectationService } from './igvaffectation'
export { useTypeIdentityDocService } from './typeidentitydoc'
export { useStandardTaxDocumentService } from './standardTaxDocuments'
